#!/system/bin/sh


#Remove app

mount -o remount,rw /system;

rm -rf /system/app/Apollo.apk
rm -rf /system/app/CMFileManager.apk
rm -rf /system/app/Term.apk
rm -rf /system/app/CMWallpapers.apk
rm -rf /system/app/CMHome.apk
rm -rf /system/app/Gmail2.apk
rm -rf /system/app/GenieWidget.apk
rm -rf /system/app/Magazines.apk
rm -rf /system/app/PlusOne.apk
rm -rf /system/app/Street.apk
rm -rf /system/app/Videos.apk
rm -rf /system/priv-app/Trebuchet.apk
rm -rf /system/priv-app/CMUpdater.apk
rm -rf /system/priv-app/VoiceDialer.apk

# Now Launcher
mkdir /data/app
mkdir /data/app-lib/com.google.android.launcher-2
cp /system/priv-app/com.google.android.launcher-2.apk /data/app/com.google.android.launcher-2.apk
rm -rf /system/priv-app/com.google.android.launcher-2.apk
cp /system/app-lib/libgoogle_hotword_jni.so /system/lib/libgoogle_hotword_jni.so
cp /system/app-lib/libgoogle_recognizer_jni_l.so /system/lib/libgoogle_recognizer_jni_l.so
cp /system/app-lib/libvcdecoder_jni.so /system/lib/libvcdecoder_jni.so

mount -o remount,ro /system;
