#!/system/bin/sh


#Remove app

mount -o remount,rw /system;

rm -rf /system/app/Apollo.apk
rm -rf /system/app/CMFileManager.apk
rm -rf /system/app/Term.apk
rm -rf /system/app/Books.apk
rm -rf /system/app/Gmail2.apk
rm -rf /system/app/Hangouts.apk
rm -rf /system/app/Maps.apk
rm -rf /system/app/Magazines.apk
rm -rf /system/app/Music2.apk
rm -rf /system/app/PlayGames.apk
rm -rf /system/app/PlusOne.apk
rm -rf /system/app/Street.apk
rm -rf /system/app/Videos.apk
rm -rf /system/app/YouTube.apk

mount -o remount,ro /system;
